
/* File generated by gen_cfile.py. Should not be modified. */

#include "SmartDisplayHost.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 Obj01_type = 0x0;		/* Mapped at index 0x2000, subindex 0x01 */
UNS8 Obj01_reserve1 = 0x0;		/* Mapped at index 0x2000, subindex 0x02 */
INTEGER16 Obj01_posX = 0x0;		/* Mapped at index 0x2000, subindex 0x03 */
INTEGER16 Obj01_posY = 0x0;		/* Mapped at index 0x2000, subindex 0x04 */
UNS16 Obj01_style = 0x0;		/* Mapped at index 0x2000, subindex 0x05 */
INTEGER16 Obj01_reserve2 = 0x0;		/* Mapped at index 0x2000, subindex 0x06 */
UNS16 Obj01_setValue = 0x0;		/* Mapped at index 0x2000, subindex 0x07 */
UNS16 Obj01_getValue = 0x0;		/* Mapped at index 0x2000, subindex 0x08 */
UNS8 Obj01_reserve3 = 0x0;		/* Mapped at index 0x2000, subindex 0x09 */
UNS8 Obj02_type = 0x0;		/* Mapped at index 0x2001, subindex 0x01 */
UNS8 Obj02_reserve1 = 0x0;		/* Mapped at index 0x2001, subindex 0x02 */
INTEGER16 Obj02_posX = 0x0;		/* Mapped at index 0x2001, subindex 0x03 */
INTEGER16 Obj02_posY = 0x0;		/* Mapped at index 0x2001, subindex 0x04 */
UNS16 Obj02_style = 0x0;		/* Mapped at index 0x2001, subindex 0x05 */
INTEGER16 Obj02_reserve2 = 0x0;		/* Mapped at index 0x2001, subindex 0x06 */
UNS16 Obj02_setValue = 0x0;		/* Mapped at index 0x2001, subindex 0x07 */
UNS16 Obj02_getValue = 0x0;		/* Mapped at index 0x2001, subindex 0x08 */
UNS8 Obj02_reserve3 = 0x0;		/* Mapped at index 0x2001, subindex 0x09 */
UNS8 Obj03_type = 0x0;		/* Mapped at index 0x2002, subindex 0x01 */
UNS8 Obj03_reserve1 = 0x0;		/* Mapped at index 0x2002, subindex 0x02 */
INTEGER16 Obj03_posX = 0x0;		/* Mapped at index 0x2002, subindex 0x03 */
INTEGER16 Obj03_posY = 0x0;		/* Mapped at index 0x2002, subindex 0x04 */
UNS16 Obj03_style = 0x0;		/* Mapped at index 0x2002, subindex 0x05 */
INTEGER16 Obj03_reserve2 = 0x0;		/* Mapped at index 0x2002, subindex 0x06 */
UNS16 Obj03_setValue = 0x0;		/* Mapped at index 0x2002, subindex 0x07 */
UNS16 Obj03_getValue = 0x0;		/* Mapped at index 0x2002, subindex 0x08 */
UNS8 Obj03_reserve3 = 0x0;		/* Mapped at index 0x2002, subindex 0x09 */
UNS8 Obj04_type = 0x0;		/* Mapped at index 0x2003, subindex 0x01 */
UNS8 Obj04_reserve1 = 0x0;		/* Mapped at index 0x2003, subindex 0x02 */
INTEGER16 Obj04_posX = 0x0;		/* Mapped at index 0x2003, subindex 0x03 */
INTEGER16 Obj04_posY = 0x0;		/* Mapped at index 0x2003, subindex 0x04 */
UNS16 Obj04_style = 0x0;		/* Mapped at index 0x2003, subindex 0x05 */
INTEGER16 Obj04_reserve2 = 0x0;		/* Mapped at index 0x2003, subindex 0x06 */
UNS16 Obj04_setValue = 0x0;		/* Mapped at index 0x2003, subindex 0x07 */
UNS16 Obj04_getValue = 0x0;		/* Mapped at index 0x2003, subindex 0x08 */
UNS8 Obj04_reserve3 = 0x0;		/* Mapped at index 0x2003, subindex 0x09 */
UNS8 Obj05_type = 0x0;		/* Mapped at index 0x2004, subindex 0x01 */
UNS8 Obj05_reserve1 = 0x0;		/* Mapped at index 0x2004, subindex 0x02 */
INTEGER16 Obj05_posX = 0x0;		/* Mapped at index 0x2004, subindex 0x03 */
INTEGER16 Obj05_posY = 0x0;		/* Mapped at index 0x2004, subindex 0x04 */
UNS16 Obj05_style = 0x0;		/* Mapped at index 0x2004, subindex 0x05 */
INTEGER16 Obj05_reserve2 = 0x0;		/* Mapped at index 0x2004, subindex 0x06 */
UNS16 Obj05_setValue = 0x0;		/* Mapped at index 0x2004, subindex 0x07 */
UNS16 Obj05_getValue = 0x0;		/* Mapped at index 0x2004, subindex 0x08 */
UNS8 Obj05_reserve3 = 0x0;		/* Mapped at index 0x2004, subindex 0x09 */
UNS8 Obj06_type = 0x0;		/* Mapped at index 0x2005, subindex 0x01 */
UNS8 Obj06_reserve1 = 0x0;		/* Mapped at index 0x2005, subindex 0x02 */
INTEGER16 Obj06_posX = 0x0;		/* Mapped at index 0x2005, subindex 0x03 */
INTEGER16 Obj06_posY = 0x0;		/* Mapped at index 0x2005, subindex 0x04 */
UNS16 Obj06_style = 0x0;		/* Mapped at index 0x2005, subindex 0x05 */
INTEGER16 Obj06_reserve2 = 0x0;		/* Mapped at index 0x2005, subindex 0x06 */
UNS16 Obj06_setValue = 0x0;		/* Mapped at index 0x2005, subindex 0x07 */
UNS16 Obj06_getValue = 0x0;		/* Mapped at index 0x2005, subindex 0x08 */
UNS8 Obj06_reserve3 = 0x0;		/* Mapped at index 0x2005, subindex 0x09 */
UNS8 Obj07_type = 0x0;		/* Mapped at index 0x2006, subindex 0x01 */
UNS8 Obj07_reserve1 = 0x0;		/* Mapped at index 0x2006, subindex 0x02 */
INTEGER16 Obj07_posX = 0x0;		/* Mapped at index 0x2006, subindex 0x03 */
INTEGER16 Obj07_posY = 0x0;		/* Mapped at index 0x2006, subindex 0x04 */
UNS16 Obj07_style = 0x0;		/* Mapped at index 0x2006, subindex 0x05 */
INTEGER16 Obj07_reserve2 = 0x0;		/* Mapped at index 0x2006, subindex 0x06 */
UNS16 Obj07_setValue = 0x0;		/* Mapped at index 0x2006, subindex 0x07 */
UNS16 Obj07_getValue = 0x0;		/* Mapped at index 0x2006, subindex 0x08 */
UNS8 Obj07_reserve3 = 0x0;		/* Mapped at index 0x2006, subindex 0x09 */
UNS8 Obj08_type = 0x0;		/* Mapped at index 0x2007, subindex 0x01 */
UNS8 Obj08_reserve1 = 0x0;		/* Mapped at index 0x2007, subindex 0x02 */
INTEGER16 Obj08_posX = 0x0;		/* Mapped at index 0x2007, subindex 0x03 */
INTEGER16 Obj08_posY = 0x0;		/* Mapped at index 0x2007, subindex 0x04 */
UNS16 Obj08_style = 0x0;		/* Mapped at index 0x2007, subindex 0x05 */
INTEGER16 Obj08_reserve2 = 0x0;		/* Mapped at index 0x2007, subindex 0x06 */
UNS16 Obj08_setValue = 0x0;		/* Mapped at index 0x2007, subindex 0x07 */
UNS16 Obj08_getValue = 0x0;		/* Mapped at index 0x2007, subindex 0x08 */
UNS8 Obj08_reserve3 = 0x0;		/* Mapped at index 0x2007, subindex 0x09 */
UNS8 Obj09_type = 0x0;		/* Mapped at index 0x2008, subindex 0x01 */
UNS8 Obj09_reserve1 = 0x0;		/* Mapped at index 0x2008, subindex 0x02 */
INTEGER16 Obj09_posX = 0x0;		/* Mapped at index 0x2008, subindex 0x03 */
INTEGER16 Obj09_posY = 0x0;		/* Mapped at index 0x2008, subindex 0x04 */
UNS16 Obj09_style = 0x0;		/* Mapped at index 0x2008, subindex 0x05 */
INTEGER16 Obj09_reserve2 = 0x0;		/* Mapped at index 0x2008, subindex 0x06 */
UNS16 Obj09_setValue = 0x0;		/* Mapped at index 0x2008, subindex 0x07 */
UNS16 Obj09_getValue = 0x0;		/* Mapped at index 0x2008, subindex 0x08 */
UNS8 Obj09_reserve3 = 0x0;		/* Mapped at index 0x2008, subindex 0x09 */
UNS8 Obj10_type = 0x0;		/* Mapped at index 0x2009, subindex 0x01 */
UNS8 Obj10_reserve1 = 0x0;		/* Mapped at index 0x2009, subindex 0x02 */
INTEGER16 Obj10_posX = 0x0;		/* Mapped at index 0x2009, subindex 0x03 */
INTEGER16 Obj10_posY = 0x0;		/* Mapped at index 0x2009, subindex 0x04 */
UNS16 Obj10_style = 0x0;		/* Mapped at index 0x2009, subindex 0x05 */
INTEGER16 Obj10_reserve2 = 0x0;		/* Mapped at index 0x2009, subindex 0x06 */
UNS16 Obj10_setValue = 0x0;		/* Mapped at index 0x2009, subindex 0x07 */
UNS16 Obj10_getValue = 0x0;		/* Mapped at index 0x2009, subindex 0x08 */
UNS8 Obj10_reserve3 = 0x0;		/* Mapped at index 0x2009, subindex 0x09 */
UNS8 Buzzer_Cycle = 0x1;		/* Mapped at index 0x2102, subindex 0x01 */
UNS8 Buzzer_High = 0x0;		/* Mapped at index 0x2102, subindex 0x02 */
UNS8 Buzzer_Low = 0x0;		/* Mapped at index 0x2102, subindex 0x03 */
UNS8 Buzzer_Active = 0x1;		/* Mapped at index 0x2102, subindex 0x04 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 SmartDisplayHost_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 SmartDisplayHost_bDeviceNodeId = 0x01;

/**************************************************************************/
/* Array of message processing information */

const UNS8 SmartDisplayHost_iam_a_slave = 0;

TIMER_HANDLE SmartDisplayHost_heartBeatTimers[2] = {TIMER_NONE,TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 SmartDisplayHost_obj1000 = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 SmartDisplayHost_obj1001 = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1001, NULL }
                     };

/* index 0x1002 :   Manufacturer Status Register. */
                    UNS32 SmartDisplayHost_obj1002 = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index1002[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1002, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1003[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SmartDisplayHost_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1003[0], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1003[1], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1003[2], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1003[3], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1003[4], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1003[5], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1003[6], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1003[7], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1003[8], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1003[9], NULL }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 SmartDisplayHost_obj1005 = 0x80000080;	/* 2147483776 */
                    subindex SmartDisplayHost_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1005, NULL }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 SmartDisplayHost_obj1006 = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1006, NULL }
                     };

/* index 0x1007 :   Synchronous Window Length. */
                    UNS32 SmartDisplayHost_obj1007 = 0xFA00;	/* 64000 */
                    subindex SmartDisplayHost_Index1007[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1007, NULL }
                     };

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 SmartDisplayHost_obj1008[12] = "Winstar Host";
                    subindex SmartDisplayHost_Index1008[] = 
                     {
                       { RO, visible_string, 12, (void*)&SmartDisplayHost_obj1008, NULL }
                     };

/* index 0x1009 :   Manufacturer Hardware Version. */
                    UNS8 SmartDisplayHost_obj1009[10] = "1.0";
                    subindex SmartDisplayHost_Index1009[] = 
                     {
                       { RO, visible_string, 10, (void*)&SmartDisplayHost_obj1009, NULL }
                     };

/* index 0x100A :   Manufacturer Software Version. */
                    UNS8 SmartDisplayHost_obj100A[10] = "1.0";
                    subindex SmartDisplayHost_Index100A[] = 
                     {
                       { RO, visible_string, 10, (void*)&SmartDisplayHost_obj100A, NULL }
                     };

/* index 0x100C :   Guard Time. */
                    UNS16 SmartDisplayHost_obj100C = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index100C[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SmartDisplayHost_obj100C, NULL }
                     };

/* index 0x100D :   Life Time Factor. */
                    UNS8 SmartDisplayHost_obj100D = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index100D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj100D, NULL }
                     };

/* index 0x1010 :   Store parameters. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1010 = 3; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1010_Save_All_Parameters = 0x0;	/* 0 */
                    UNS32 SmartDisplayHost_obj1010_Save_Communication_Parameters = 0x0;	/* 0 */
                    UNS32 SmartDisplayHost_obj1010_Save_Application_Parameters = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index1010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1010, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1010_Save_All_Parameters, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1010_Save_Communication_Parameters, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1010_Save_Application_Parameters, NULL }
                     };

/* index 0x1011 :   Restore Default Parameters. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1011 = 3; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1011_Restore_All_Default_Parameters = 0x0;	/* 0 */
                    UNS32 SmartDisplayHost_obj1011_Restore_Communication_Default_Parameters = 0x0;	/* 0 */
                    UNS32 SmartDisplayHost_obj1011_Restore_Application_Default_Parameters = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index1011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1011, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1011_Restore_All_Default_Parameters, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1011_Restore_Communication_Default_Parameters, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1011_Restore_Application_Default_Parameters, NULL }
                     };

/* index 0x1012 :   TIME COB ID. */
                    UNS32 SmartDisplayHost_obj1012 = 0x80000100;	/* 2147483904 */
                    subindex SmartDisplayHost_Index1012[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1012, NULL }
                     };

/* index 0x1013 :   High Resolution Timestamp. */
                    UNS32 SmartDisplayHost_obj1013 = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index1013[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1013, NULL }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 SmartDisplayHost_obj1014 = 0x80;	/* 128 */
                    subindex SmartDisplayHost_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1014, NULL }
                     };

/* index 0x1015 :   Inhibit Time Emergency. */
                    UNS16 SmartDisplayHost_obj1015 = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index1015[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SmartDisplayHost_obj1015, NULL }
                     };

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1016 = 2; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1016[] = 
                    {
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SmartDisplayHost_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1016, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1016[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1016[1], NULL }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 SmartDisplayHost_obj1017 = 0x7D0;	/* 2000 */
                    subindex SmartDisplayHost_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SmartDisplayHost_obj1017, NULL }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 SmartDisplayHost_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 SmartDisplayHost_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 SmartDisplayHost_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1018_Serial_Number, NULL }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 SmartDisplayHost_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex SmartDisplayHost_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1200, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1200_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1200_COB_ID_Server_to_Client_Transmit_SDO, NULL }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x600 + 0x7B;	/* 1536 */
                    UNS32 SmartDisplayHost_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x580 + 0x7B;	/* 1408 */
                    UNS8 SmartDisplayHost_obj1280_Node_ID_of_the_SDO_Server = 0x7B;	/* 1 */
                    subindex SmartDisplayHost_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1280, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1280_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1280_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1280_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1400_COB_ID_used_by_PDO = 0x1FB;	/* 512 */
                    UNS8 SmartDisplayHost_obj1400_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 SmartDisplayHost_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SmartDisplayHost_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SmartDisplayHost_obj1400_Event_Timer = 0x32;	/* 50 */
                    UNS8 SmartDisplayHost_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SmartDisplayHost_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SmartDisplayHost_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1401_COB_ID_used_by_PDO = 0x2FB;	/* 768 */
                    UNS8 SmartDisplayHost_obj1401_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 SmartDisplayHost_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SmartDisplayHost_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SmartDisplayHost_obj1401_Event_Timer = 0x32;	/* 50 */
                    UNS8 SmartDisplayHost_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SmartDisplayHost_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SmartDisplayHost_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1402_COB_ID_used_by_PDO = 0x3FB;	/* 1024 */
                    UNS8 SmartDisplayHost_obj1402_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 SmartDisplayHost_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SmartDisplayHost_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SmartDisplayHost_obj1402_Event_Timer = 0x32;	/* 50 */
                    UNS8 SmartDisplayHost_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SmartDisplayHost_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SmartDisplayHost_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1402_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1600 = 4; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1600[] = 
                    {
                      0x20000810,	/* 536872976 */
                      0x20010810,	/* 536938512 */
                      0x20020810,	/* 537004048 */
                      0x20030810	/* 537069584 */
                    };
                    subindex SmartDisplayHost_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1600[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1600[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1600[3], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1601 = 4; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1601[] = 
                    {
                      0x20040810,	/* 537135120 */
                      0x20050810,	/* 537200656 */
                      0x20060810,	/* 537266192 */
                      0x20070810	/* 537331728 */
                    };
                    subindex SmartDisplayHost_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1601[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1601[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1601[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1601[3], NULL }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1602 = 4; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1602[] = 
                    {
                      0x20080810,	/* 537397264 */
                      0x20090810,	/* 537462800 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SmartDisplayHost_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1602, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1602[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1602[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1602[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1602[3], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1800_COB_ID_used_by_PDO = 0x27B;	/* 384 */
                    UNS8 SmartDisplayHost_obj1800_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 SmartDisplayHost_obj1800_Inhibit_Time = 0;	/* 0 */
                    UNS8 SmartDisplayHost_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SmartDisplayHost_obj1800_Event_Timer = 0x64;	/* 100 */
                    UNS8 SmartDisplayHost_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SmartDisplayHost_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SmartDisplayHost_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1801_COB_ID_used_by_PDO = 0x37B;	/* 640 */
                    UNS8 SmartDisplayHost_obj1801_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 SmartDisplayHost_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SmartDisplayHost_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SmartDisplayHost_obj1801_Event_Timer = 0x64;	/* 100 */
                    UNS8 SmartDisplayHost_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SmartDisplayHost_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SmartDisplayHost_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1801_SYNC_start_value, NULL }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1802_COB_ID_used_by_PDO = 0x47B;	/* 896 */
                    UNS8 SmartDisplayHost_obj1802_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 SmartDisplayHost_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SmartDisplayHost_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SmartDisplayHost_obj1802_Event_Timer = 0x64;	/* 100 */
                    UNS8 SmartDisplayHost_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    subindex SmartDisplayHost_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SmartDisplayHost_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SmartDisplayHost_obj1802_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_obj1802_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1A00 = 4; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1A00[] = 
                    {
                      0x20000710,	/* 536872720 */
                      0x20010710,	/* 536938256 */
                      0x20020710,	/* 537003792 */
                      0x20030710	/* 537069328 */
                    };
                    subindex SmartDisplayHost_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1A00[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1A00[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1A00[3], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1A01 = 4; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1A01[] = 
                    {
                      0x20040710,	/* 537134864 */
                      0x20050710,	/* 537200400 */
                      0x20060710,	/* 537265936 */
                      0x20070710	/* 537331472 */
                    };
                    subindex SmartDisplayHost_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1A01[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1A01[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1A01[3], NULL }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 SmartDisplayHost_highestSubIndex_obj1A02 = 3; /* number of subindex - 1*/
                    UNS32 SmartDisplayHost_obj1A02[] = 
                    {
                      0x20080710,	/* 537397008 */
                      0x20090710,	/* 537462544 */
                      0x0	/* 0 */
                    };
                    subindex SmartDisplayHost_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1A02[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1A02[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SmartDisplayHost_obj1A02[2], NULL }
                     };

/* index 0x2000 :   Mapped variable Obj01 */
                    UNS8 SmartDisplayHost_highestSubIndex_obj2000 = 9; /* number of subindex - 1*/
                    subindex SmartDisplayHost_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj2000, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Obj01_type, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj01_reserve1, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj01_posX, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj01_posY, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj01_style, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj01_reserve2, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj01_setValue, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj01_getValue, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj01_reserve3, NULL }
                     };

/* index 0x2001 :   Mapped variable Obj02 */
                    UNS8 SmartDisplayHost_highestSubIndex_obj2001 = 9; /* number of subindex - 1*/
                    subindex SmartDisplayHost_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj2001, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Obj02_type, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj02_reserve1, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj02_posX, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj02_posY, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj02_style, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj02_reserve2, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj02_setValue, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj02_getValue, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj02_reserve3, NULL }
                     };

/* index 0x2002 :   Mapped variable Obj03 */
                    UNS8 SmartDisplayHost_highestSubIndex_obj2002 = 9; /* number of subindex - 1*/
                    subindex SmartDisplayHost_Index2002[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj2002, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Obj03_type, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj03_reserve1, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj03_posX, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj03_posY, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj03_style, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj03_reserve2, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj03_setValue, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj03_getValue, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj03_reserve3, NULL }
                     };

/* index 0x2003 :   Mapped variable Obj04 */
                    UNS8 SmartDisplayHost_highestSubIndex_obj2003 = 9; /* number of subindex - 1*/
                    subindex SmartDisplayHost_Index2003[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj2003, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Obj04_type, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj04_reserve1, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj04_posX, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj04_posY, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj04_style, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj04_reserve2, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj04_setValue, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj04_getValue, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj04_reserve3, NULL }
                     };

/* index 0x2004 :   Mapped variable Obj05 */
                    UNS8 SmartDisplayHost_highestSubIndex_obj2004 = 9; /* number of subindex - 1*/
                    subindex SmartDisplayHost_Index2004[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj2004, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Obj05_type, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj05_reserve1, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj05_posX, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj05_posY, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj05_style, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj05_reserve2, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj05_setValue, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj05_getValue, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj05_reserve3, NULL }
                     };

/* index 0x2005 :   Mapped variable Obj06 */
                    UNS8 SmartDisplayHost_highestSubIndex_obj2005 = 9; /* number of subindex - 1*/
                    subindex SmartDisplayHost_Index2005[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj2005, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Obj06_type, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj06_reserve1, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj06_posX, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj06_posY, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj06_style, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj06_reserve2, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj06_setValue, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj06_getValue, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj06_reserve3, NULL }
                     };

/* index 0x2006 :   Mapped variable Obj07 */
                    UNS8 SmartDisplayHost_highestSubIndex_obj2006 = 9; /* number of subindex - 1*/
                    subindex SmartDisplayHost_Index2006[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj2006, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Obj07_type, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj07_reserve1, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj07_posX, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj07_posY, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj07_style, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj07_reserve2, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj07_setValue, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj07_getValue, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj07_reserve3, NULL }
                     };

/* index 0x2007 :   Mapped variable Obj08 */
                    UNS8 SmartDisplayHost_highestSubIndex_obj2007 = 9; /* number of subindex - 1*/
                    subindex SmartDisplayHost_Index2007[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj2007, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Obj08_type, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj08_reserve1, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj08_posX, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj08_posY, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj08_style, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj08_reserve2, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj08_setValue, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj08_getValue, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj08_reserve3, NULL }
                     };

/* index 0x2008 :   Mapped variable Obj09 */
                    UNS8 SmartDisplayHost_highestSubIndex_obj2008 = 9; /* number of subindex - 1*/
                    subindex SmartDisplayHost_Index2008[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj2008, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Obj09_type, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj09_reserve1, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj09_posX, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj09_posY, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj09_style, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj09_reserve2, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj09_setValue, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj09_getValue, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj09_reserve3, NULL }
                     };

/* index 0x2009 :   Mapped variable Obj10 */
                    UNS8 SmartDisplayHost_highestSubIndex_obj2009 = 9; /* number of subindex - 1*/
                    subindex SmartDisplayHost_Index2009[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj2009, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Obj10_type, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj10_reserve1, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj10_posX, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj10_posY, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj10_style, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Obj10_reserve2, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj10_setValue, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Obj10_getValue, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Obj10_reserve3, NULL }
                     };

/* index 0x2102 :   Mapped variable Buzzer */
                    UNS8 SmartDisplayHost_highestSubIndex_obj2102 = 4; /* number of subindex - 1*/
                    subindex SmartDisplayHost_Index2102[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SmartDisplayHost_highestSubIndex_obj2102, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Buzzer_Cycle, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Buzzer_High, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Buzzer_Low, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Buzzer_Active, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable SmartDisplayHost_objdict[] = 
{
  { (subindex*)SmartDisplayHost_Index1000,sizeof(SmartDisplayHost_Index1000)/sizeof(SmartDisplayHost_Index1000[0]), 0x1000},
  { (subindex*)SmartDisplayHost_Index1001,sizeof(SmartDisplayHost_Index1001)/sizeof(SmartDisplayHost_Index1001[0]), 0x1001},
  { (subindex*)SmartDisplayHost_Index1002,sizeof(SmartDisplayHost_Index1002)/sizeof(SmartDisplayHost_Index1002[0]), 0x1002},
  { (subindex*)SmartDisplayHost_Index1003,sizeof(SmartDisplayHost_Index1003)/sizeof(SmartDisplayHost_Index1003[0]), 0x1003},
  { (subindex*)SmartDisplayHost_Index1005,sizeof(SmartDisplayHost_Index1005)/sizeof(SmartDisplayHost_Index1005[0]), 0x1005},
  { (subindex*)SmartDisplayHost_Index1006,sizeof(SmartDisplayHost_Index1006)/sizeof(SmartDisplayHost_Index1006[0]), 0x1006},
  { (subindex*)SmartDisplayHost_Index1007,sizeof(SmartDisplayHost_Index1007)/sizeof(SmartDisplayHost_Index1007[0]), 0x1007},
  { (subindex*)SmartDisplayHost_Index1008,sizeof(SmartDisplayHost_Index1008)/sizeof(SmartDisplayHost_Index1008[0]), 0x1008},
  { (subindex*)SmartDisplayHost_Index1009,sizeof(SmartDisplayHost_Index1009)/sizeof(SmartDisplayHost_Index1009[0]), 0x1009},
  { (subindex*)SmartDisplayHost_Index100A,sizeof(SmartDisplayHost_Index100A)/sizeof(SmartDisplayHost_Index100A[0]), 0x100A},
  { (subindex*)SmartDisplayHost_Index100C,sizeof(SmartDisplayHost_Index100C)/sizeof(SmartDisplayHost_Index100C[0]), 0x100C},
  { (subindex*)SmartDisplayHost_Index100D,sizeof(SmartDisplayHost_Index100D)/sizeof(SmartDisplayHost_Index100D[0]), 0x100D},
  { (subindex*)SmartDisplayHost_Index1010,sizeof(SmartDisplayHost_Index1010)/sizeof(SmartDisplayHost_Index1010[0]), 0x1010},
  { (subindex*)SmartDisplayHost_Index1011,sizeof(SmartDisplayHost_Index1011)/sizeof(SmartDisplayHost_Index1011[0]), 0x1011},
  { (subindex*)SmartDisplayHost_Index1012,sizeof(SmartDisplayHost_Index1012)/sizeof(SmartDisplayHost_Index1012[0]), 0x1012},
  { (subindex*)SmartDisplayHost_Index1013,sizeof(SmartDisplayHost_Index1013)/sizeof(SmartDisplayHost_Index1013[0]), 0x1013},
  { (subindex*)SmartDisplayHost_Index1014,sizeof(SmartDisplayHost_Index1014)/sizeof(SmartDisplayHost_Index1014[0]), 0x1014},
  { (subindex*)SmartDisplayHost_Index1015,sizeof(SmartDisplayHost_Index1015)/sizeof(SmartDisplayHost_Index1015[0]), 0x1015},
  { (subindex*)SmartDisplayHost_Index1016,sizeof(SmartDisplayHost_Index1016)/sizeof(SmartDisplayHost_Index1016[0]), 0x1016},
  { (subindex*)SmartDisplayHost_Index1017,sizeof(SmartDisplayHost_Index1017)/sizeof(SmartDisplayHost_Index1017[0]), 0x1017},
  { (subindex*)SmartDisplayHost_Index1018,sizeof(SmartDisplayHost_Index1018)/sizeof(SmartDisplayHost_Index1018[0]), 0x1018},
  { (subindex*)SmartDisplayHost_Index1200,sizeof(SmartDisplayHost_Index1200)/sizeof(SmartDisplayHost_Index1200[0]), 0x1200},
  { (subindex*)SmartDisplayHost_Index1280,sizeof(SmartDisplayHost_Index1280)/sizeof(SmartDisplayHost_Index1280[0]), 0x1280},
  { (subindex*)SmartDisplayHost_Index1400,sizeof(SmartDisplayHost_Index1400)/sizeof(SmartDisplayHost_Index1400[0]), 0x1400},
  { (subindex*)SmartDisplayHost_Index1401,sizeof(SmartDisplayHost_Index1401)/sizeof(SmartDisplayHost_Index1401[0]), 0x1401},
  { (subindex*)SmartDisplayHost_Index1402,sizeof(SmartDisplayHost_Index1402)/sizeof(SmartDisplayHost_Index1402[0]), 0x1402},
  { (subindex*)SmartDisplayHost_Index1600,sizeof(SmartDisplayHost_Index1600)/sizeof(SmartDisplayHost_Index1600[0]), 0x1600},
  { (subindex*)SmartDisplayHost_Index1601,sizeof(SmartDisplayHost_Index1601)/sizeof(SmartDisplayHost_Index1601[0]), 0x1601},
  { (subindex*)SmartDisplayHost_Index1602,sizeof(SmartDisplayHost_Index1602)/sizeof(SmartDisplayHost_Index1602[0]), 0x1602},
  { (subindex*)SmartDisplayHost_Index1800,sizeof(SmartDisplayHost_Index1800)/sizeof(SmartDisplayHost_Index1800[0]), 0x1800},
  { (subindex*)SmartDisplayHost_Index1801,sizeof(SmartDisplayHost_Index1801)/sizeof(SmartDisplayHost_Index1801[0]), 0x1801},
  { (subindex*)SmartDisplayHost_Index1802,sizeof(SmartDisplayHost_Index1802)/sizeof(SmartDisplayHost_Index1802[0]), 0x1802},
  { (subindex*)SmartDisplayHost_Index1A00,sizeof(SmartDisplayHost_Index1A00)/sizeof(SmartDisplayHost_Index1A00[0]), 0x1A00},
  { (subindex*)SmartDisplayHost_Index1A01,sizeof(SmartDisplayHost_Index1A01)/sizeof(SmartDisplayHost_Index1A01[0]), 0x1A01},
  { (subindex*)SmartDisplayHost_Index1A02,sizeof(SmartDisplayHost_Index1A02)/sizeof(SmartDisplayHost_Index1A02[0]), 0x1A02},
  { (subindex*)SmartDisplayHost_Index2000,sizeof(SmartDisplayHost_Index2000)/sizeof(SmartDisplayHost_Index2000[0]), 0x2000},
  { (subindex*)SmartDisplayHost_Index2001,sizeof(SmartDisplayHost_Index2001)/sizeof(SmartDisplayHost_Index2001[0]), 0x2001},
  { (subindex*)SmartDisplayHost_Index2002,sizeof(SmartDisplayHost_Index2002)/sizeof(SmartDisplayHost_Index2002[0]), 0x2002},
  { (subindex*)SmartDisplayHost_Index2003,sizeof(SmartDisplayHost_Index2003)/sizeof(SmartDisplayHost_Index2003[0]), 0x2003},
  { (subindex*)SmartDisplayHost_Index2004,sizeof(SmartDisplayHost_Index2004)/sizeof(SmartDisplayHost_Index2004[0]), 0x2004},
  { (subindex*)SmartDisplayHost_Index2005,sizeof(SmartDisplayHost_Index2005)/sizeof(SmartDisplayHost_Index2005[0]), 0x2005},
  { (subindex*)SmartDisplayHost_Index2006,sizeof(SmartDisplayHost_Index2006)/sizeof(SmartDisplayHost_Index2006[0]), 0x2006},
  { (subindex*)SmartDisplayHost_Index2007,sizeof(SmartDisplayHost_Index2007)/sizeof(SmartDisplayHost_Index2007[0]), 0x2007},
  { (subindex*)SmartDisplayHost_Index2008,sizeof(SmartDisplayHost_Index2008)/sizeof(SmartDisplayHost_Index2008[0]), 0x2008},
  { (subindex*)SmartDisplayHost_Index2009,sizeof(SmartDisplayHost_Index2009)/sizeof(SmartDisplayHost_Index2009[0]), 0x2009},
  { (subindex*)SmartDisplayHost_Index2102,sizeof(SmartDisplayHost_Index2102)/sizeof(SmartDisplayHost_Index2102[0]), 0x2102},
};

const indextable * SmartDisplayHost_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1002: i = 2;break;
		case 0x1003: i = 3;break;
		case 0x1005: i = 4;break;
		case 0x1006: i = 5;break;
		case 0x1007: i = 6;break;
		case 0x1008: i = 7;break;
		case 0x1009: i = 8;break;
		case 0x100A: i = 9;break;
		case 0x100C: i = 10;break;
		case 0x100D: i = 11;break;
		case 0x1010: i = 12;break;
		case 0x1011: i = 13;break;
		case 0x1012: i = 14;break;
		case 0x1013: i = 15;break;
		case 0x1014: i = 16;break;
		case 0x1015: i = 17;break;
		case 0x1016: i = 18;break;
		case 0x1017: i = 19;break;
		case 0x1018: i = 20;break;
		case 0x1200: i = 21;break;
		case 0x1280: i = 22;break;
		case 0x1400: i = 23;break;
		case 0x1401: i = 24;break;
		case 0x1402: i = 25;break;
		case 0x1600: i = 26;break;
		case 0x1601: i = 27;break;
		case 0x1602: i = 28;break;
		case 0x1800: i = 29;break;
		case 0x1801: i = 30;break;
		case 0x1802: i = 31;break;
		case 0x1A00: i = 32;break;
		case 0x1A01: i = 33;break;
		case 0x1A02: i = 34;break;
		case 0x2000: i = 35;break;
		case 0x2001: i = 36;break;
		case 0x2002: i = 37;break;
		case 0x2003: i = 38;break;
		case 0x2004: i = 39;break;
		case 0x2005: i = 40;break;
		case 0x2006: i = 41;break;
		case 0x2007: i = 42;break;
		case 0x2008: i = 43;break;
		case 0x2009: i = 44;break;
		case 0x2102: i = 45;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &SmartDisplayHost_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status SmartDisplayHost_PDO_status[3] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index SmartDisplayHost_firstIndex = {
  21, /* SDO_SVR */
  22, /* SDO_CLT */
  23, /* PDO_RCV */
  26, /* PDO_RCV_MAP */
  29, /* PDO_TRS */
  32 /* PDO_TRS_MAP */
};

const quick_index SmartDisplayHost_lastIndex = {
  21, /* SDO_SVR */
  22, /* SDO_CLT */
  25, /* PDO_RCV */
  28, /* PDO_RCV_MAP */
  31, /* PDO_TRS */
  34 /* PDO_TRS_MAP */
};

const UNS16 SmartDisplayHost_ObjdictSize = sizeof(SmartDisplayHost_objdict)/sizeof(SmartDisplayHost_objdict[0]); 

CO_Data SmartDisplayHost_Data = CANOPEN_NODE_DATA_INITIALIZER(SmartDisplayHost);

